baseURL = "https://lucas.blotta.info"
languageCode = "en-us"
title = "Lucas Blotta"
theme = "temple"

[params]
    highlight = true
    topmenu = "categories"

[taxonomies]
    tag = "tags"
    category = "categories"

[author]
    name = "Lucas Blotta"
    github = "blotta"